<?php


namespace app\modules\structure\widgets;



use app\modules\structure\models\Department;
use yii\widgets\InputWidget;

use yii\base\InvalidConfigException;

use yii\helpers\Html;
use yii\helpers\ArrayHelper;

use app\modules\hr\models\DictionaryWord;


class DepartmentInputWidget extends InputWidget
{
    /**
     * @throws InvalidConfigException
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (!$this->hasModel()) {
            throw new InvalidConfigException('Use InputWidget only with model');
        }
    }

    /**
     * 
     */
    public function run()
    {
        Html::addCssClass($this->options, ['form-control']);
        $this->options['prompt'] = '';
        $items = Department::treeItemsForDropDownList('-');
        echo Html::activeDropDownList($this->model, $this->attribute, $items, $this->options);
    }

}
